import Head from 'next/head'
import React from "react";
import CalendarTable from '../components/CalendarTable'

export default function Home() {
    return (
        <>
            <Head>
                <title>kosmo-calendar</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/calendar_icon.png"/>
            </Head>
            <main>
                <div className={'container mx-auto mt-6'}>
                    <CalendarTable/>
                </div>
            </main>
        </>
    )
}
