import Head from 'next/head'
import {useEffect, useState} from "react";

export default function Home() {

    const [message, setMessage] = useState('empty message');

    useEffect(() => {
        fetch('/api/hello')
            .then((response) => response.json())
            .then((data) => {
                setMessage(data.msg);
            })
            .catch((err) => {
                console.log(err.message);
            });
    }, []);

    return (
        <>
            <Head>
                <title>kosmo-calendar</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/calendar_icon.png"/>
            </Head>
            <main>
                <div>
                    <h1 className="text-3xl font-bold">
                        {message}
                    </h1>
                </div>
            </main>
        </>
    )
}
